#### 00. Pytorch Fundamentals

In [1]:
print("Hello I am Shaheer Abdullah and excited to learn this course !!")

Hello I am Shaheer Abdullah and excited to learn this course !!


In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Introduction To Tensors

In [4]:
#Scaler-Tensors
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
#To get back the integer
scaler.item()

7

In [7]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [45]:
vector[1]

tensor(7)

In [8]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
 # Matrix
MATRIX =torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [47]:
MATRIX[1][1]

tensor(10)

In [13]:
MATRIX.ndim

2

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape #Depends upon the square Brackets

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [39]:
TENSOR3 = torch.tensor([[[[1,2,3,5],
                          [3,4,5,7],
                          [1,2,3,5],
                          [1,2,3,4],
                          [3,4,5,6]]]])

In [40]:
TENSOR3.shape

torch.Size([1, 1, 5, 4])

In [41]:
TENSOR3.ndim

4

In [42]:
TENSOR3[0][0][1][3]

tensor(7)

### Random Tensors

In [78]:
### Random Tensors in brackets give the dimension 3 rows 4 columns
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1221, 0.5380, 0.9834, 0.4910],
        [0.8544, 0.6460, 0.9613, 0.1550],
        [0.6829, 0.2935, 0.8169, 0.4988]])

In [51]:
random_tensor[0][1]

tensor(0.3493)

In [52]:
random_tensor.ndim

2

In [53]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[0.0668, 0.2369, 0.0490, 0.6973, 0.2195, 0.3855, 0.4637, 0.9892,
          0.8881, 0.4311],
         [0.4177, 0.1791, 0.8430, 0.2897, 0.3537, 0.7977, 0.4618, 0.0629,
          0.4367, 0.3118],
         [0.7424, 0.5498, 0.3846, 0.7014, 0.6224, 0.4697, 0.1546, 0.6090,
          0.4811, 0.0229],
         [0.7144, 0.2746, 0.8295, 0.4694, 0.5920, 0.6106, 0.3188, 0.9444,
          0.5959, 0.9935],
         [0.0099, 0.8090, 0.6230, 0.0696, 0.6177, 0.0172, 0.4501, 0.8709,
          0.4397, 0.3101],
         [0.5641, 0.0235, 0.7415, 0.4215, 0.1585, 0.5840, 0.9170, 0.8383,
          0.3168, 0.3336],
         [0.1029, 0.6916, 0.9961, 0.5053, 0.7887, 0.0264, 0.4707, 0.4635,
          0.3764, 0.1569],
         [0.0421, 0.3910, 0.7219, 0.2893, 0.7180, 0.4006, 0.2232, 0.2232,
          0.2852, 0.9055],
         [0.3837, 0.3815, 0.6846, 0.9123, 0.7085, 0.1920, 0.3660, 0.5380,
          0.8257, 0.5311],
         [0.7205, 0.8568, 0.5178, 0.2490, 0.9405, 0.8265, 0.8074, 0.8827,
          0.4891,

In [54]:
random_tensor.ndim

3

In [55]:
random_tensor[0][2][0]

tensor(0.7424)

In [58]:
#Create a random tensor with the siilar shape to image

random_image_Size_tensor =torch.rand(size=(3,224,224)) ,#cannel RGB,#height , #width
random_image_Size_tensor.ndim , random_image_Size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [62]:
random_torch1 = torch.rand(2,4)
random_torch1

tensor([[0.3294, 0.0807, 0.9502, 0.0377],
        [0.6187, 0.2025, 0.3563, 0.0671]])

In [64]:
random_torch1[1][1]

tensor(0.2025)

In [69]:
random_tensor2 = torch.rand(3,10,10)
random_tensor2

tensor([[[0.4856, 0.5056, 0.7748, 0.0768, 0.2946, 0.6849, 0.4603, 0.2469,
          0.2250, 0.9165],
         [0.5384, 0.5596, 0.9779, 0.9840, 0.2698, 0.9529, 0.7282, 0.1236,
          0.7380, 0.3255],
         [0.6445, 0.6691, 0.1797, 0.9456, 0.1277, 0.1922, 0.9627, 0.0336,
          0.3285, 0.4472],
         [0.4897, 0.1610, 0.8414, 0.1021, 0.6613, 0.1348, 0.0040, 0.5760,
          0.8969, 0.7091],
         [0.4513, 0.6563, 0.3130, 0.3719, 0.5276, 0.7365, 0.8364, 0.9323,
          0.6494, 0.0625],
         [0.5529, 0.4050, 0.8719, 0.1784, 0.9329, 0.8827, 0.1432, 0.3477,
          0.2728, 0.1857],
         [0.1428, 0.9162, 0.6374, 0.9970, 0.0574, 0.2476, 0.0261, 0.7457,
          0.4890, 0.4048],
         [0.8255, 0.2970, 0.5460, 0.8067, 0.7743, 0.1972, 0.7803, 0.4623,
          0.7892, 0.6063],
         [0.9244, 0.7370, 0.2137, 0.7450, 0.5980, 0.4879, 0.8585, 0.6543,
          0.1575, 0.2325],
         [0.1754, 0.8824, 0.4165, 0.1222, 0.5372, 0.7738, 0.7631, 0.6763,
          0.4807,

In [71]:
random_tensor2[1][1][1]

tensor(0.8737)

In [73]:
random_tensor3 = torch.rand(size=(1,10,10))
random_tensor3

tensor([[[0.3905, 0.3725, 0.0643, 0.7941, 0.0675, 0.2721, 0.6276, 0.8744,
          0.3127, 0.3535],
         [0.3617, 0.7647, 0.1191, 0.3407, 0.4647, 0.3369, 0.7716, 0.7233,
          0.8903, 0.2054],
         [0.6142, 0.9081, 0.7354, 0.1191, 0.0446, 0.2522, 0.2952, 0.0454,
          0.0783, 0.5207],
         [0.7126, 0.1720, 0.8351, 0.7147, 0.5400, 0.5138, 0.1869, 0.9178,
          0.5255, 0.8555],
         [0.7280, 0.3503, 0.4186, 0.8398, 0.0652, 0.7417, 0.9102, 0.3340,
          0.8466, 0.7549],
         [0.1959, 0.5913, 0.0036, 0.0406, 0.8326, 0.5853, 0.8903, 0.2565,
          0.7170, 0.4515],
         [0.7171, 0.3520, 0.9915, 0.5114, 0.7719, 0.5917, 0.1468, 0.9519,
          0.0810, 0.9738],
         [0.7578, 0.8453, 0.8362, 0.5423, 0.6211, 0.1943, 0.8268, 0.6521,
          0.4014, 0.1966],
         [0.0847, 0.6149, 0.6521, 0.5271, 0.9560, 0.1531, 0.5659, 0.9583,
          0.3377, 0.2682],
         [0.7285, 0.9505, 0.8665, 0.1272, 0.9984, 0.0153, 0.5221, 0.3064,
          0.1081,

### Zeros & ones Tensor

In [76]:
### Zeros & ones Tensor
zeros_tensor =torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [77]:
#Ones Tensor
ones_tensor = torch.ones(size=(3,4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [79]:
zeros_tensor * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [80]:
ones_tensor * random_tensor

tensor([[0.1221, 0.5380, 0.9834, 0.4910],
        [0.8544, 0.6460, 0.9613, 0.1550],
        [0.6829, 0.2935, 0.8169, 0.4988]])

In [82]:
random_tensor.dtype

torch.float32

In [83]:
# Always tensor dtype is float32 by default unless you cahnge it.
ones_tensor.dtype

torch.float32

In [90]:
#use tensor.arange()
one_to_ten1= torch.arange(start=0,end=10)
one_to_ten1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#use tensor.arange()
one_to_ten = torch.arange(start=0,end=1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [89]:
#creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
example_tensor = torch.arange(start=1,end=12,step=2)
example_tensor

tensor([ 1,  3,  5,  7,  9, 11])

In [92]:
tensor_like = torch.ones_like(input=example_tensor)
tensor_like # same output size as above

tensor([1, 1, 1, 1, 1, 1])

### Tensor Data-Type

In [105]:
float_32_tensor = torch.tensor([3.5,4.0,5.0],
                               dtype=None,
                               device="cpu",
                               requires_grad=True)
float_32_tensor

tensor([3.5000, 4.0000, 5.0000], requires_grad=True)

In [106]:
float_32_tensor.dtype

torch.float32

In [107]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.5000, 4.0000, 5.0000], dtype=torch.float16,
       grad_fn=<ToCopyBackward0>)

In [108]:
float_16_tensor * float_32_tensor

tensor([12.2500, 16.0000, 25.0000], grad_fn=<MulBackward0>)

In [111]:
int_32_tensor = float_16_tensor.type(torch.LongTensor)
int_32_tensor

tensor([3, 4, 5])

In [112]:
int_32_tensor * float_32_tensor

tensor([10.5000, 16.0000, 25.0000], grad_fn=<MulBackward0>)

### Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [113]:
#Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0302, 0.6515, 0.0363, 0.4319],
        [0.5871, 0.3345, 0.6670, 0.4019],
        [0.6975, 0.3691, 0.5648, 0.1793]])

In [118]:
#Find the details
print(some_tensor)
print(f"\nData_type of tensor is: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0302, 0.6515, 0.0363, 0.4319],
        [0.5871, 0.3345, 0.6670, 0.4019],
        [0.6975, 0.3691, 0.5648, 0.1793]])

Data_type of tensor is: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [140]:
#Practice
random_tensor = torch.rand(4,4)
print(random_tensor)
print(random_tensor.dtype)
random_tensor = random_tensor.type(torch.float16)
print(random_tensor)
print(random_tensor.dtype)

tensor([[0.5842, 0.1656, 0.4543, 0.6700],
        [0.6195, 0.7462, 0.5167, 0.1032],
        [0.0740, 0.5424, 0.9009, 0.0063],
        [0.2115, 0.6038, 0.1469, 0.0795]])
torch.float32
tensor([[0.5840, 0.1655, 0.4543, 0.6699],
        [0.6196, 0.7461, 0.5166, 0.1032],
        [0.0740, 0.5425, 0.9009, 0.0063],
        [0.2114, 0.6040, 0.1469, 0.0795]], dtype=torch.float16)
torch.float16


In [141]:
print(random_tensor.shape)
print(random_tensor.device)
print(random_tensor.dtype)

torch.Size([4, 4])
cpu
torch.float16
