### Manipulating Tensors (Tensor Operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication
* Multiplication(Element Wise)

In [59]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [60]:
#create a tensor
tensor1 = torch.tensor([1,2,3])
tensor1 + 100

tensor([101, 102, 103])

In [61]:
# Multiply
tensor1 * 10

tensor([10, 20, 30])

In [62]:
tensor1 #is still that as i have'nt assigned it

tensor([1, 2, 3])

In [63]:
tensor1 = tensor1 * 10

In [64]:
tensor1

tensor([10, 20, 30])

In [65]:
tensor1/10

tensor([1., 2., 3.])

In [66]:
# Builtin funcitons
torch.mul(tensor1,10)

tensor([100, 200, 300])

In [67]:
torch.add(tensor1,10)

tensor([20, 30, 40])

In [68]:
torch.sub(tensor1,10)

tensor([ 0, 10, 20])

In [69]:
torch.divide(tensor1,10)

tensor([1., 2., 3.])

In [70]:
# Matrix Multiplication
tensor1=torch.tensor([4,5,6])

In [71]:
print(tensor1, "*" ,tensor1)
print(f"{tensor1 * tensor1}")

tensor([4, 5, 6]) * tensor([4, 5, 6])
tensor([16, 25, 36])


In [72]:
torch.matmul(tensor1,tensor1)

tensor(77)

In [73]:
# As the no.of columns of first tensor is not equal to the no. of rows of 2nd column.
tensor2=torch.tensor([4,5,6])
tensor3=torch.tensor([2,4])
torch.matmul(tensor2,tensor3)

RuntimeError: inconsistent tensor size, expected tensor [3] and src [2] to have the same number of elements, but got 3 and 2 elements respectively

In [76]:
%%time
value =0

for i in range(len(tensor2)):
  value += tensor2[i]*tensor2[i]
value

CPU times: user 1.64 ms, sys: 11 µs, total: 1.65 ms
Wall time: 1.46 ms


tensor(77)

In [77]:
#More optimized Uses vectorization method.
%%time
torch.matmul(tensor2,tensor2)

CPU times: user 90 µs, sys: 7 µs, total: 97 µs
Wall time: 101 µs


tensor(77)

In [78]:
%%time
tensor2 @ tensor2

CPU times: user 899 µs, sys: 0 ns, total: 899 µs
Wall time: 917 µs


tensor(77)

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [79]:
#Inner dimensions must be same.
torch.matmul(torch.rand(2,3),torch.rand(2,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [80]:
#result will be in outer dimension in this case 2 x 2.
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.5502, 0.7746],
        [0.8111, 1.1318]])

In [81]:
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[2.6305, 2.3386, 2.8128],
        [3.0635, 2.9736, 3.1752],
        [2.1967, 2.4488, 3.0028]])

In [82]:
#Shapes for Matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [86]:
#To fix the Shape issue use the Transpose function
torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [83]:
print(tensor_A.shape)

torch.Size([3, 2])


In [84]:
print(tensor_B.shape)

torch.Size([3, 2])


In [85]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [91]:
print(f"Original Shapes : tensor_A = {tensor_A.shape} tensor_B = {tensor_B.shape}")
print(f"New Shapes : tensor_A = {tensor_A.shape} tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions must match")
print(f"\nOutput Shape : {torch.matmul(tensor_A,tensor_B.T)}")
print(f"\nOutput Shape : {torch.matmul(tensor_A,tensor_B.T).shape}")

Original Shapes : tensor_A = torch.Size([3, 2]) tensor_B = torch.Size([3, 2])
New Shapes : tensor_A = torch.Size([3, 2]) tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions must match

Output Shape : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output Shape : torch.Size([3, 3])
