###  02_PyTorch_Fundamentals_09July

### Tensor Aggregations

In [2]:
## Finding the mean,max,sum etc (Tensor Aggregations)
import torch
x = torch.arange(start=0,end=100,step=10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
#Find the min.
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [4]:
#Find the max.
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [5]:
#Find the mean.
#for mean its necessary that you should have dtype of float.
x = x.type(torch.float32)
print(torch.mean(x))
print(torch.mean(x.type(torch.float32)))

tensor(45.)
tensor(45.)


In [6]:
torch.sum(x)

tensor(450.)

In [7]:
x.sum()

tensor(450.)

In [8]:
#Positional min and max.
#x.argmin() will return the index of minimum value.
x.argmin()

tensor(0)

In [9]:
x[0]

tensor(0.)

In [10]:
#x.argmin() will return the index of maxmimum value.
x.argmax()

tensor(9)

In [11]:
x[9]

tensor(90.)

In [12]:
tensor_example=torch.rand(2,2)
tensor_example

tensor([[0.8029, 0.4544],
        [0.1058, 0.4232]])

In [15]:
tensor_example.min() , torch.min(tensor_example)

(tensor(0.1058), tensor(0.1058))

In [16]:
tensor_example.max(), torch.max(tensor_example)

(tensor(0.8029), tensor(0.8029))

In [17]:
tensor_example.sum()

tensor(1.7863)

In [18]:
tensor_example.argmin()

tensor(2)

In [22]:
tensor_example.argmax()

tensor(0)

In [23]:
torch.mean(tensor_example.type(torch.float32))

tensor(0.4466)

### Reshape, View , Squeeze, Unsqueeze, Stack,Permute

In [40]:
#Reshaping
x = torch.arange(start=1.,end=10.)

In [41]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [42]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [43]:
#change the view (quite similar to reshape)
z =  x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
#changes x will change the z. as thery are sharing same memory.
x[0] = 55
x,z

(tensor([55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]))

In [50]:
#Stack tensors on top of each other.
x_stacked =torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [51]:
x_stacked =torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[55., 55., 55., 55.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [52]:
#torch.squeeze() -- reomves all single dimensions from target tensors
x_reshaped

tensor([[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [54]:
x_reshaped.shape

torch.Size([1, 9])

In [57]:
x_reshaped.shape , x_reshaped.squeeze().shape

(torch.Size([1, 9]), torch.Size([9]))

In [61]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"New_Shape: {x_squeezed.shape}")
# Will remove all the one dimensions from the array.
print(f"New_Tensor: {x_squeezed}")

Previous tensor: tensor([[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
Previous Shape: torch.Size([1, 9])
New_Shape: torch.Size([9])
New_Tensor: tensor([55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])


In [67]:
print(f"Previous-Target: {x_squeezed}")
print(f"previous-Shape: {x_squeezed.shape}")
#torch.unsqueeze add a single dimension to a target tensor at a specific dim.
x_unsqueezed  = x_squeezed.unsqueeze(dim=0)
print(f"New_Tensor: {x_unsqueezed}")
print(f"New_Shape: {x_unsqueezed.shape}")

Previous-Target: tensor([55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
previous-Shape: torch.Size([9])
New_Tensor: tensor([[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
New_Shape: torch.Size([1, 9])


In [70]:
#torch.permute function rearranges the dimensions of tensor
x_original = torch.rand(size=(224,224,3))
print(f"previous_shape:{x_original.shape}")
#After Permutation
X_permuted = x_original.permute(2,0,1)
print(f"New_Shape: {X_permuted.shape}") #channles,height,width

previous_shape:torch.Size([224, 224, 3])
New_Shape: torch.Size([3, 224, 224])


In [72]:
x_original[0][0][0] = 9999

In [73]:
X_permuted[0][0][0]  #This also work as view.

tensor(9999.)

In [75]:
## Indexing with pyTorch
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
x[0,1,1] #or x[0][1][1]

tensor(5)

In [80]:
x[0][2][2]

tensor(9)

In [86]:
x[:,:, 1]

tensor([[2, 5, 8]])

In [87]:
x[0][1][1]

tensor(5)

In [92]:
x[0][2][2]

tensor(9)

In [94]:
x[:,:, 2]

tensor([[3, 6, 9]])

### Pytorch Tensors & Numpy

In [99]:
#Numpy array to tensor
#By default it uses same as numpy float64
import numpy as np
import torch
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [100]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float32)

In [101]:
array = array+1 # does not change the value of tensor.
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [105]:
#Tensor to Array
tensor_numpy = torch.ones(7)
numpy_array = tensor_numpy.numpy()
tensor_numpy.dtype , numpy_array.dtype

(torch.float32, dtype('float32'))

In [106]:
tensor_numpy =tensor_numpy+1
tensor_numpy,numpy_array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))