### Tensors to Numpy and Numpy to Tensors

In [2]:
import torch
import numpy as np
#Tensor-to-numpy
example_Tensor = torch.rand(2,3)
example_Tensor

tensor([[0.9698, 0.6916, 0.1046],
        [0.7302, 0.8890, 0.9324]])

In [3]:
example_numpy = example_Tensor.numpy()
print(example_numpy)

[[0.9698452  0.69164705 0.10455215]
 [0.7302477  0.8889857  0.93241656]]


In [4]:
example_Tensor.dtype , example_numpy.dtype

(torch.float32, dtype('float32'))

In [5]:
array1 = np.arange(1.0 , 8.0)
array1 = array1 + 1
print(array1)

[2. 3. 4. 5. 6. 7. 8.]


In [6]:
tensor = torch.from_numpy(array1)
print(tensor)

tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [7]:
array1.dtype ,  tensor.dtype

(dtype('float64'), torch.float64)

In [8]:
random_tensor=torch.rand(2,2)
random_tensor

tensor([[0.4865, 0.7142],
        [0.4830, 0.7769]])

In [9]:
ones_Tensor = torch.ones_like(random_tensor)
print(ones_Tensor)

tensor([[1., 1.],
        [1., 1.]])


### Reproducibility (Trying to take random out of random)  Random seed


In [10]:
#Before Reproducibility
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B )

tensor([[0.6289, 0.2381, 0.5601, 0.6766],
        [0.4573, 0.4122, 0.0918, 0.8639],
        [0.2529, 0.2682, 0.9420, 0.6166]])
tensor([[0.8243, 0.9972, 0.8329, 0.5172],
        [0.8195, 0.7680, 0.1376, 0.4797],
        [0.6797, 0.3431, 0.9257, 0.2164]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


#### manual_seed works with only one block of code so if you want it to execute again and again you have to use it again and again

In [11]:
#After Reproducibility
#Lets make some random but reproducible tensors
import torch
#set the random seed
RANDOM_SEED = 42
# set the torch manual
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

#set the random seed
# set the torch manual
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D )

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on GPUs

In [12]:
!nvidia-smi

Wed Jul 10 18:08:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [13]:
## 2. check for GPU access
#if GPU is available it will return True.
torch.cuda.is_available()

True

In [19]:
# Setup device agnostic code
device = ''
if torch.cuda.is_available():
  device = 'gpu'
else:
  device = 'cpu'


In [20]:
device

'gpu'

In [21]:
# Count number of devices
torch.cuda.device_count()

1